### ISSUE TITLE
visualisation bugs with viewer

### ISSUE THREAD

**Issue by lbesnard** [aodn/auv#24]
As reported by Neville Barrett who actively uses the viewer
(edit : he confirmed me that the following glintches are only recent)
Example around this location 
```
Lon: 151.26242
Lat: -34.00703
```

Many visualisation bugs exist at different zoom level

** Medium zoom level
The two dives (visible with a yellow auv icon), aren't always visible. The one on the right disappears at a certain zoom level.

and clicking on the icons don't always give results

** track zoom level
The track is not displayed all the time as a track anymore (? maybe due to the last openlayer update ?). Random dots appear, and if the user keep on zooming, he will eventually see the proper track

another good example is with the Tasmania 2015 campaign at 
```
Lon: 146.28512
Lat: -43.74408
```

**Comment by lbesnard** [comment]
@danfruehauf , @pblain , could this be the result of upgrading  openlayers?

**Comment by danfruehauf** [comment]
@lbesnard  OpenLayers was never upgraded for AUV.

**Comment by pmbohm** [comment]
@lbesnard 
I have made lots of changes that fix bugs encountered and also improvements which help discovering issues with data. A pull request to come. In the mean time I have found that quite a few tracks have no geometry column, that you could fix?

### SQL
```

select site_code
from auv_viewer_track.auv_tracks_vw
 where geom is null;

```
### Answer

"r20101119_204443_site6guz_10_densegrids"
"r20101119_224028_site6guz_11_densegrid3"
"r20121128_051532_Tollgates_site4sz_04_broad"
"r20111124_021850_hendersonNth_04_grids_shallow"
"r20121128_195806_Burrewarra_BU_DG3_05_dense"
"r20121128_225241_Lilli_Pilli_LP_DG2_06_dense"
"r20111124_225113_hendersonSth_06_mid_grids"
"r20121129_011610_Lilli_Pilli_LP_DG2_07_broad"
"r20071006_001140_gbr_07_viper_grids"
"r20111125_010449_hendersonSth_06_mid_grids"
"r20131021_050804_hendersonNth_01_broad"
"r20131021_215646_hendersonSth_02_broad"
"r20110228_040127_station1190_07_broad"
"r20110301_012810_station1195_09_transect"
"r20110717_032905_01_seagrass_double_grids_site_741"
"r20131022_211529_hendersonNth_05_grids"
"r20110718_012407_02_seagrass_overlapping_grids_site_1190"
"r20131022_232116_hendersonNth_06_grids2"
"r20110718_051123_03_seagrass_double_grids_site_1182"
"r20110719_001932_04_seagrass_double_grids_site_1195"
"r20090726_074343_scott_05_long_transect_auv2"
"r20110719_033935_05_seagrass_double_grids_site_1202"
"r20090727_002236_scott_06_long_transect_auv5"
"r20110719_063108_06_seagrass_double_grids_site_1199"
"r20090727_085810_scott_07_grids_auv2"
"r20110720_021728_08_seagrass_double_grids_site_2281"
"r20090728_004240_scott_08_long_transect_auv4"
"r20090728_074740_scott_09_long_transect_auv1"
"r20110721_073950_13_seagrass_double_grids_site_2084"
"r20110721_230829_14_seagrass_double_grids_site_1188"
"r20090730_001654_scott_13_long_transect_auv6"
"r20090730_084520_scott_14_dense_survey_auv6_shallow"
"r20110723_000020_18_myrmidon_reef_NW_long_grids"
"r20090731_021940_scott_15_grids_shallow_auv2"
"r20090731_084031_scott_17_grids_deep_auv3"
"r20110723_220055_20_myrmidon_reef_NW_triple_grids"
"r20090731_235129_scott_18_grids_shallow_auv1"
"r20110724_033943_21_myrmidon_reef_SW_triple_grids"
"r20090802_012719_scott_20_long_transect_auv8"
"r20110725_055449_23_helix_reef_NW_double_grids"
"r20090803_081411_scott_23_grids_shallow_auv8"
"r20071011_043724_gbr_10_hydrographers_grid_leg"
"r20110722_045421_16_helix_reef_NW_double_grids"
"r20121212_065358_01_seagrass_double_grids_site_741"
"r20090729_072005_scott_11_dense_survey_auv5_deep"
"r20110723_044414_19_mymidon_reef_NE_triple_grids"
"r20131022_030905_hendersonSth_04_mid_deep_grids"
"r20131212_000027_04_seagrass_double_lines_site_1188"
"r20131022_004934_hendersonSth_03_shallow_grids"
"r20071012_042111_gbr_11_hydrographers_shoal_sandwaves"
"r20121213_221602_02_seagrass_overlapping_grids_site_1190"
"r20090801_084142_scott_19_grids_deep_auv1"
"r20121214_015257_03_seagrass_double_grids_site_1195"
"r20110722_041610_15_helix_reef_NW_double_grids"
"r20071010_230932_gbr_09_hydrographers_leg"
"r20110720_060344_09_seagrass_double_grids_site_2083"
"r20090729_003637_scott_10_long_transect_auv3"
"r20110725_002121_22_thimble_shoals_triple_grids"
"r20131023_021600_hendersonNth_07_grids3"
"r20121214_043214_04_seagrass_double_grids_site_1182"
"r20131211_220037_03_seagrass_double_lines_site_1195"
"r20131212_025025_05_seagrass_double_lines_site_1202"
"r20131212_042216_06_seagrass_double_lines_site_1199"
"r20131213_010858_07_seagrass_double_lines_site_2281"
"r20131213_030450_08_seagrass_double_lines_site_1631"
"r20131213_052712_09_seagrass_double_lines_site_2083"
"r20131213_221028_10_seagrass_double_lines_site_2543"
"r20131214_011423_11_seagrass_double_lines_site_2441"
"r20101021_035013_hendersonSth_04_broad"
"r20101021_234246_hendersonNth_05_broad"
"r20101022_051840_hendersonNth_07_grids_deep"
"r20101022_220331_hendersonNth_08_grids_shallow"
"r20101023_002251_hendersonNth_09_grids_shallow"
"r20111122_230036_hendersonSth_01_shallow_grids"
"r20111123_235202_hendersonNth_03_grids_shallow"
"r20111124_010352_hendersonNth_04_grids_shallow"
"r20111124_012354_hendersonNth_04_grids_shallow"

**Comment by pmbohm** [comment]
These changes will be required to be done in the Geoserver repo
 and be pushed at the same time as AUV is re-deployed with the fix for this bug.
..../auv_tracks_vw/content.ftl
```
<p class="getfeatureCode" style="display:none" >AUV_${feature.site_code.value}</p>
```
to:
```
<p class="getfeatureCode" style="display:none" >${feature.site_code.value}</p>
```

.....auv_images_vw/content.ftl
```
<div class="panelinfo">${feature.dive_code_name.value?capitalize} ${feature.time.value} &nbsp; Depth:${depthNum}m
        Temperature:${feature.sea_water_temperature.value}&deg;c
        Salinity:${feature.sea_water_salinity.value}
        Chlorophyll:${feature.chlorophyll_concentration_in_sea_water.value}
</div>
```
to:
```
<div class="panelinfo">${feature.dive_code_name.value?capitalize} ${feature.time.value} &nbsp; Depth:${depthNum}m &nbsp;
        Temperature:${feature.sea_water_temperature.value}&deg;c &nbsp;
        Salinity:${feature.sea_water_salinity.value} &nbsp;
        Chlorophyll:${feature.chlorophyll_concentration_in_sea_water.value}
</div>
```
