### ISSUE TITLE
Metadata for first track in list is not displayed

### ISSUE THREAD

**Issue by jkburges** [aodn/auv#31]
Metadata for first track in list is not displayed.

**Steps to reproduce**
1. Select first track from drop down.

**What should happen**
You should see something like:

<pre>
Batemans 06 Site6guz
Start: Wed 17th Nov 2010 11:48:48AM
End: Wed 17th Nov 2010 12:41:41PM

-36.09013N	
150.1508W		150.1641E
-36.09482S	
Depth: 15.1611m -> 37.55642m
Distance: 1376.4866m
Dive Report
Link to the IMOS metadata record
Data on opendap 
Link to data folder 
Download for Google Earth (KML) 
</pre>

**What does happen**

![image](https://cloud.githubusercontent.com/assets/1849176/8791513/4ca49c3a-2f9f-11e5-972c-29792b98f0c6.png)

**Comment by lbesnard** [comment]
@jkburges , the commit was merged, but it seems like the bug is still there

**Comment by jkburges** [comment]
It's probably not been deployed yet, let me check...

**Comment by jkburges** [comment]
Indeed, this fix hasn't been deployed yet.  I am seeing to it now.

**Comment by jkburges** [comment]
Ok now @lbesnard?

**Comment by lbesnard** [comment]
beautiful ! how responsive !!
