### ISSUE TITLE
Old auv url recomissioned?

### ISSUE THREAD

**Issue by kereid** [aodn/auv#32]
Steps to reproduce:

Go to https://auv.emii.org.au/auv/

What should happen:

nothing or redirected to https://auv.aodn.org.au/auv/

What does happen:

User taken to https://auv.emii.org.au/auv/

Spoke to Loz about this and he has checked and the ip address is the same but we should not have 2 sites,

**Comment by lbesnard** [comment]
https://github.com/aodn/geoserver-config/pull/296

**Comment by lbesnard** [comment]
should be fixed @kereid

**Comment by kereid** [comment]
Doesn't appear to be... the GFI links are still going to auv.emii.org.au @lbesnard

**Comment by danfruehauf** [comment]
@lbesnard Did you deploy that change on the geoserver branch? (master -> production)

**Comment by danfruehauf** [comment]
@lbesnard @kereid Just verified it, it's not deployed. Changes are not on the `production` branch.

**Comment by lbesnard** [comment]
gotta do it

**Comment by danfruehauf** [comment]
Just verified it was deployed successfully.

**Comment by pmbohm** [comment]
Still needs a redirect rule to redirect  to auv.aodn,org.au

auv.emii.org.au is still published such as:
http://www.nespmarine.edu.au/cmr-still-image-30
