### ISSUE TITLE
AUV getFeatureInfo request failing

### ISSUE THREAD

**Issue by pmbohm** [aodn/auv#35]
### What happens

Some click points and sites dont load in the AUV viewer as they rely on getFeatureInfo responses to respond.
Below is a valid request from the AUV viewer
https://geoserver-123.aodn.org.au/geoserver/wms?LAYERS=imos%3Aauv_tracks_vw&STYLES=&SRS=EPSG%3A4326&FORMAT=image%2Fpng&TRANSPARENT=TRUE&TILED=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&EXCEPTIONS=application%2Fvnd.ogc.se_xml&BBOX=99.84375%2C-54.125%2C170.15625%2C2.125&INFO_FORMAT=text%2Fhtml&QUERY_LAYERS=imos%3Aauv_tracks_vw&FEATURE_COUNT=100&WIDTH=400&HEIGHT=320&X=83&Y=180

The Geoserver log shows 

```
Error on line 10, column 1 in content.ftl
ids[4] is undefined.
It cannot be assigned to depth
```
### What should happen

getFeatureInfo requests should never fail for `auv_tracks_vw`

**Comment by lbesnard** [comment]
@pmbohm I'm not allowed to close the ticket. I guess I just don't have enough XP

**Comment by pmbohm** [comment]
other Example request
http://localhost:8090/auv/proxy?url=https%3A%2F%2Fgeoserver-

**Comment by pmbohm** [comment]
No errors should occur because the database values are missing. THe FTL should be checked so that database values can be null
```
30 Jun 01:41:36 ERROR [freemarker.runtime] - Template processing error: "Expression feature.kml is undefined on line 7, column 25 in content.ftl."
```

**Comment by pmbohm** [comment]
More problems occurring pointing to bigger problems as @lbesnard has checked for null data
```
30 Jun 01:36:20 ERROR [freemarker.runtime] - Template processing error: "Expression feature.image_filename is undefined on line 5, column 145 in content.ftl."
Expression feature.image_filename is undefined on line 5, column 145 in content.ftl.
The problematic instruction:
----------
==> ${feature.image_filename.value} [on line 5, column 143 in content.ftl]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression feature.image_filename is undefined on line 5, column 145 in content.ftl.
```
